# Generated by Django 5.1.4 on 2024-12-12 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_categoria_fornecedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'verbose_name_plural': 'Fornecedores'},
        ),
    ]
